services:
  spring-wallet:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/spring-wallet
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.1
    container_name: spring-wallet-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spring-wallet
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10