spring:
  datasource:
    url: jdbc:postgresql://localhost:6541/spring-wallet
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: pass
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none